### round 1
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "1",
    "finishers": [1, 11, 55, 16, 63, 4, 44, 81, 14, 18],
    "dnf": []
}

### round 2
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "2",
    "finishers": [1, 11, 16, 81, 14, 63, 38, 4, 44, 27],
    "dnf": []
}

### round 3
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "3",
    "finishers": [55, 16, 4, 81, 11, 18, 22, 14, 27, 20],
    "dnf": []
}

### round 4
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "4",
    "finishers": [1, 11, 55, 16, 4, 14, 63, 81, 44, 22],
    "dnf": []
}

### round 5
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "5",
    "finishers": [1, 4, 11, 16, 55, 63, 14, 81, 44, 27],
    "dnf": []
}

### round 6
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "6",
    "finishers": [4, 1, 11, 16, 55, 44, 22, 63, 14, 31],
    "dnf": []
}

### round 7
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "7",
    "finishers": [1, 4, 16, 81, 55, 44, 63, 11, 18, 22],
    "dnf": []
}

### round 8
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "8",
    "finishers": [16, 81, 55, 4, 63, 1, 44, 22, 23, 10],
    "dnf": []
}

### round 9
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "9",
    "finishers": [1, 4, 63, 44, 81, 14, 18, 3, 10, 31],
    "dnf": []
}

### round 10
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "10",
    "finishers": [1, 4, 44, 63, 16, 55, 81, 11, 10, 31],
    "dnf": []
}
### round 11
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "11",
    "finishers": [63, 81, 55, 44, 1, 27, 11, 20, 3, 10],
    "dnf": []
}

### round 12
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "12",
    "finishers": [44, 1, 4, 81, 55, 27, 18, 14, 23, 22],
    "dnf": []
}

### round 13
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "13",
    "finishers": [81, 4, 44, 16, 1, 55, 11, 63, 22, 18],
    "dnf": []
}

### round 14
POST http://localhost:5000/api/v1/addraceresults/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root",
    "rd": "14",
    "finishers": [44, 81, 16, 1, 4, 55, 11, 14, 31, 3],
    "dnf": []
}