### tests base server
GET http://localhost:5000/

### tests mongodb connection
GET http://localhost:5000/test/

### creates base user
POST http://localhost:5000/api/v1/createusers/
Content-Type: application/json

{
    "name": "John Doe",
    "passwd": "123"
}

### shows list of all users
GET http://localhost:5000/api/v1/getusers/
Content-Type: application/json

{
    "name": "root",
    "passwd": "root"
}

### shows all race results
GET http://localhost:5000/api/v1/checkallraceresults

### push user predictions
POST http://localhost:5000/api/v1/userpredictions/
Content-Type: application/json

{
    "name": "John Doe",
    "passwd": "123",
    "rd": "1",
    "predictions": [1, 11, 55, 16, 4, 14, 63, 81, 44, 22]
}

### shows user predictions
GET http://localhost:5000/api/v1/userpredictions
Content-Type: application/json

{
    "name": "John Doe",
    "passwd": "123",
    "rd": "1"
}

### shows user predictions
GET http://localhost:5000/api/v1/validatepredictions
Content-Type: application/json

{
    "authname": "root",
    "authpasswd": "root",
    "rd": "1",
    "name": "John Doe"
}
